import streamlit as st
from agents.Query import SQLagent
from agents.SummaringAgent import summarizeTable
from agents.Plotting import plotGraphs
from agents.MapAgent import generateMap
import os
import pandas as pd

# === Streamlit Config ===
# st.set_page_config(page_title="🌊 FloatChat - Ocean Data Agent", layout="wide")

st.title("🌊 FloatChat - Ocean Data Exploration")
st.markdown("Query the oceanographic database using natural language and get summaries.")

# === Chat History (session state) ===
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display previous chat messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("summary"):
            st.subheader("📌 Summary")
            st.write(msg["summary"])
        if msg.get("figures"):
            st.subheader("📊 Visualization")
            for fig in msg["figures"]:
                st.pyplot(fig)
        if msg.get("map_html"):
            st.subheader("🗺️ Map Preview")
            st.components.v1.html(msg["map_html"], height=500, scrolling=True)

# === User Input ===
if user_input := st.chat_input("🔍 Enter your query..."):
    st.session_state.messages.append({"role": "user", "content": user_input})

    with st.chat_message("user"):
        st.markdown(user_input)

    with st.chat_message("assistant"):
        with st.spinner("Extracting data..."):
            sql_query = SQLagent(user_input)

        if sql_query and sql_query.get("result"):
            st.success("✅ Data extracted successfully!")
            sql_string = sql_query["sql_query"]
            map_html = generateMap(sql_string)
            sql_query = sql_query.get("sql_query", "")
            st.subheader("📝 Generated SQL Query")
            st.code(sql_query, language="sql")

            st.subheader("🗺️ Map Preview")
            st.components.v1.html(map_html, height=500, scrolling=True)



            # CSV path generated by SQLagent
            project_root = os.path.dirname(os.path.abspath(__file__))
            csv_path = os.path.join(project_root, "dataExtracted.csv")

            if os.path.exists(csv_path):
                df = pd.read_csv(csv_path)
                st.subheader("📊 Extracted Data Preview")

                n = len(df)
                if n > 10:
                    top = df.head(5)
                    bottom = df.tail(5)
                    # Create a separator row with "..."
                    sep = pd.DataFrame([["..." for _ in df.columns]], columns=df.columns)
                    combined_df = pd.concat([top, sep, bottom], ignore_index=True)
                elif n > 5:
                    top = df.head(5)
                    bottom = df.tail(n - 5)
                    sep = pd.DataFrame([["..." for _ in df.columns]], columns=df.columns)
                    combined_df = pd.concat([top, sep, bottom], ignore_index=True)
                else:
                    combined_df = df

                st.dataframe(combined_df, use_container_width=True)
                st.markdown(f"**Total Entries:** {n}")

                with open(csv_path, "rb") as f:
                    st.download_button(
                        label="⬇️ Download Extracted CSV",
                        data=f,
                        file_name="dataExtracted.csv",
                        mime="text/csv"
                    )

                # Summarize data
                with st.spinner("📝 Summarizing extracted data..."):
                    summary, visualizations = summarizeTable(user_input, csv_path)

                if summary:
                    st.subheader("📌 Summary")
                    st.write(summary)

                # Plot graphs
                figures = plotGraphs(csv_path, visualizations)
                if figures:
                    st.subheader("📊 Visualization")
                    for fig in figures:
                        st.pyplot(fig)
                else:
                    st.warning("No valid plots generated.")



                # Save assistant response in history
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": "Here are your query results:",
                    "summary": summary,
                    "figures": figures,
                    "map_html": map_html
                })
            else:
                st.error("CSV file not found after SQL execution.")
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": "⚠️ CSV file not found after SQL execution."
                })
        else:
            st.error("⚠️ Query failed or returned no results.")
            st.session_state.messages.append({
                "role": "assistant",
                "content": "⚠️ Query failed or returned no results."
            })
